services:
  - type: web
    name: aqi-backend
    runtime: python
    env: python3
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: app/firebase.json
